use_frameworks!

platform :ios, '10.0'

target 'RyTransitioningDelegate_Example' do
  pod 'RyTransitioningDelegate', :path => '../'

  target 'RyTransitioningDelegate_Tests' do
    inherit! :search_paths

    
  end
end
